### ISSUE TITLE
[Feature] <Search bar on home screen in mobile view>

### ISSUE THREAD

**Issue by abhiraj-ku** [rupali-codes/LinksHub#304]
### Description

Hey ,

I think there should be a search bar on the home-screen itself in the mobile view so that the user visiting the site for the time should not have to look for the search-bar or they might even leave the site .

I am open for suggestions .. Thanks in Advance

**Comment by rupali-codes** [comment]
@abhiraj-ku Hi,
Good catch, so where you would want to place it?

**Comment by abhiraj-ku** [comment]
![Linkshub issue](https://user-images.githubusercontent.com/113116498/222919768-136c8371-d2c9-4cc0-9122-2e3d55ede7c9.png)

@rupali-codes  maybe shifting the linkshub title upwards and placing the searchbar right there and also remove the text that is below linkshub heading right now , because in the mobile view we don't need that..

I hope this helps

**Comment by rupali-codes** [comment]
Nice, @abhiraj-ku can we make it like this, ignore the three dots

![image](https://user-images.githubusercontent.com/78981177/222923211-e79c63e9-3552-43c7-9a4d-7576a05ab4f0.png)

**Comment by abhiraj-ku** [comment]
@rupali-codes  maybe but again isn't it the same as the hamburger menu already there . The search bar should be there in the center and social icon should be in the footer.  and in the placeholder there should be something like "search for resources of animations, colors ..." 

Above footer there should be something like "want to add a feature or report a bug ,click here" with a github link to this repo. in this way user interested in contributing will be keen to look at the code  rather than just a github icon with link. 

Again this is just a suggestion from my side while navigating the site for sometime. I am free to discussions ..All the very best for this awesome project .Thanks

**Comment by rupali-codes** [comment]
@abhiraj-ku thanks, we will be putting icons in sidebar except theme toggler, checkout [this](https://github.com/rupali-codes/LinksHub/pull/303). 
Do you have any suggestions now?

**Comment by ujjawaltyagii** [comment]
@abhiraj-ku Yes, I think the logo in sidemenu (in mobile screen) should be moved to footer and one more thing I want to add is that we should make search bar visible only when user taps on search icon.

what do you think about it ? @rupali-codes

**Comment by abhiraj-ku** [comment]
@rupali-codes I have given a suggestion about the contribution button . I hope you will find it useful (refer to my previous comment)

**Comment by rupali-codes** [comment]
> @abhiraj-ku Yes, I think the logo in sidemenu (in mobile screen) should be moved to footer and one more thing I want to add is that we should make search bar visible only when user taps on search icon(in mobile view only).
> 
> what do you think about it ? @rupali-codes

seems nice though...

**Comment by shindodkar** [comment]
is it open?

**Comment by rupali-codes** [comment]
> is it open?

Yes, would you like to work on this?

**Comment by rupali-codes** [comment]
Yeah, this issue has been resolved

**Comment by shindodkar** [comment]
Hii  @rupali-codes I still can't figure out which file to make changes ,were to make changes .Would you suggest me some tips to overwhelme this?

**Comment by rupali-codes** [comment]
> Hii @rupali-codes I still can't figure out which file to make changes ,were to make changes .Would you suggest me some tips to overwhelme this?

Hey, this issue was fixed, you can look for some other issues ☺️

**Comment by abhiraj-ku** [comment]
Great ☺️
